markdown: kramdown
highlighter: null
permalink: pretty
url: https://websharpstudios.com/
plugins:
  - jekyll-redirect-from
include:
  - _images
  - _static
socialTitle: websharpstudios
socialDescription: websharpstudios is a free and open-source outline font editor.
socialImage: /assets/img/social-banner.png
socialAuthor: '@websharpstudios'
